// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: poem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Poem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Contents      []string               `protobuf:"bytes,3,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poem) Reset() {
	*x = Poem{}
	mi := &file_poem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poem) ProtoMessage() {}

func (x *Poem) ProtoReflect() protoreflect.Message {
	mi := &file_poem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poem.ProtoReflect.Descriptor instead.
func (*Poem) Descriptor() ([]byte, []int) {
	return file_poem_proto_rawDescGZIP(), []int{0}
}

func (x *Poem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Poem) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Poem) GetContents() []string {
	if x != nil {
		return x.Contents
	}
	return nil
}

type PoemCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []*Poem                `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoemCollection) Reset() {
	*x = PoemCollection{}
	mi := &file_poem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoemCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoemCollection) ProtoMessage() {}

func (x *PoemCollection) ProtoReflect() protoreflect.Message {
	mi := &file_poem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoemCollection.ProtoReflect.Descriptor instead.
func (*PoemCollection) Descriptor() ([]byte, []int) {
	return file_poem_proto_rawDescGZIP(), []int{1}
}

func (x *PoemCollection) GetValue() []*Poem {
	if x != nil {
		return x.Value
	}
	return nil
}

type StreamPoem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to OneOf:
	//
	//	*StreamPoem_Title
	//	*StreamPoem_Author
	//	*StreamPoem_Content
	OneOf         isStreamPoem_OneOf `protobuf_oneof:"OneOf"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPoem) Reset() {
	*x = StreamPoem{}
	mi := &file_poem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPoem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPoem) ProtoMessage() {}

func (x *StreamPoem) ProtoReflect() protoreflect.Message {
	mi := &file_poem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPoem.ProtoReflect.Descriptor instead.
func (*StreamPoem) Descriptor() ([]byte, []int) {
	return file_poem_proto_rawDescGZIP(), []int{2}
}

func (x *StreamPoem) GetOneOf() isStreamPoem_OneOf {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *StreamPoem) GetTitle() string {
	if x != nil {
		if x, ok := x.OneOf.(*StreamPoem_Title); ok {
			return x.Title
		}
	}
	return ""
}

func (x *StreamPoem) GetAuthor() string {
	if x != nil {
		if x, ok := x.OneOf.(*StreamPoem_Author); ok {
			return x.Author
		}
	}
	return ""
}

func (x *StreamPoem) GetContent() string {
	if x != nil {
		if x, ok := x.OneOf.(*StreamPoem_Content); ok {
			return x.Content
		}
	}
	return ""
}

type isStreamPoem_OneOf interface {
	isStreamPoem_OneOf()
}

type StreamPoem_Title struct {
	Title string `protobuf:"bytes,1,opt,name=title,proto3,oneof"`
}

type StreamPoem_Author struct {
	Author string `protobuf:"bytes,2,opt,name=author,proto3,oneof"`
}

type StreamPoem_Content struct {
	Content string `protobuf:"bytes,3,opt,name=content,proto3,oneof"`
}

func (*StreamPoem_Title) isStreamPoem_OneOf() {}

func (*StreamPoem_Author) isStreamPoem_OneOf() {}

func (*StreamPoem_Content) isStreamPoem_OneOf() {}

type GetPoemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoemRequest) Reset() {
	*x = GetPoemRequest{}
	mi := &file_poem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoemRequest) ProtoMessage() {}

func (x *GetPoemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoemRequest.ProtoReflect.Descriptor instead.
func (*GetPoemRequest) Descriptor() ([]byte, []int) {
	return file_poem_proto_rawDescGZIP(), []int{3}
}

func (x *GetPoemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UploadPoemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndTime       string                 `protobuf:"bytes,1,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data          []*Poem                `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPoemResponse) Reset() {
	*x = UploadPoemResponse{}
	mi := &file_poem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPoemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPoemResponse) ProtoMessage() {}

func (x *UploadPoemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPoemResponse.ProtoReflect.Descriptor instead.
func (*UploadPoemResponse) Descriptor() ([]byte, []int) {
	return file_poem_proto_rawDescGZIP(), []int{4}
}

func (x *UploadPoemResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UploadPoemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadPoemResponse) GetData() []*Poem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_poem_proto protoreflect.FileDescriptor

const file_poem_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"poem.proto\x1a\x1bgoogle/protobuf/empty.proto\"P\n" +
	"\x04Poem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1a\n" +
	"\bcontents\x18\x03 \x03(\tR\bcontents\"-\n" +
	"\x0ePoemCollection\x12\x1b\n" +
	"\x05value\x18\x01 \x03(\v2\x05.PoemR\x05value\"c\n" +
	"\n" +
	"StreamPoem\x12\x16\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x12\x18\n" +
	"\x06author\x18\x02 \x01(\tH\x00R\x06author\x12\x1a\n" +
	"\acontent\x18\x03 \x01(\tH\x00R\acontentB\a\n" +
	"\x05OneOf\"&\n" +
	"\x0eGetPoemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"d\n" +
	"\x12UploadPoemResponse\x12\x19\n" +
	"\bend_time\x18\x01 \x01(\tR\aendTime\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x19\n" +
	"\x04data\x18\x03 \x03(\v2\x05.PoemR\x04data2\xb1\x03\n" +
	"\vPoemService\x12#\n" +
	"\aGetPoem\x12\x0f.GetPoemRequest\x1a\x05.Poem\"\x00\x121\n" +
	"\rGetPoemStream\x12\x0f.GetPoemRequest\x1a\v.StreamPoem\"\x000\x01\x127\n" +
	"\n" +
	"GetPoemAll\x12\x16.google.protobuf.Empty\x1a\x0f.PoemCollection\"\x00\x125\n" +
	"\x10GetPoemAllStream\x12\x16.google.protobuf.Empty\x1a\x05.Poem\"\x000\x01\x12*\n" +
	"\n" +
	"UploadPoem\x12\x05.Poem\x1a\x13.UploadPoemResponse\"\x00\x128\n" +
	"\x10UploadPoemStream\x12\v.StreamPoem\x1a\x13.UploadPoemResponse\"\x00(\x01\x129\n" +
	"\x0fBatchUploadPoem\x12\x0f.PoemCollection\x1a\x13.UploadPoemResponse\"\x00\x129\n" +
	"\x15BatchUploadPoemStream\x12\x05.Poem\x1a\x13.UploadPoemResponse\"\x00(\x010\x01B\n" +
	"Z\b./proto;b\x06proto3"

var (
	file_poem_proto_rawDescOnce sync.Once
	file_poem_proto_rawDescData []byte
)

func file_poem_proto_rawDescGZIP() []byte {
	file_poem_proto_rawDescOnce.Do(func() {
		file_poem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poem_proto_rawDesc), len(file_poem_proto_rawDesc)))
	})
	return file_poem_proto_rawDescData
}

var file_poem_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_poem_proto_goTypes = []any{
	(*Poem)(nil),               // 0: Poem
	(*PoemCollection)(nil),     // 1: PoemCollection
	(*StreamPoem)(nil),         // 2: StreamPoem
	(*GetPoemRequest)(nil),     // 3: GetPoemRequest
	(*UploadPoemResponse)(nil), // 4: UploadPoemResponse
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_poem_proto_depIdxs = []int32{
	0,  // 0: PoemCollection.value:type_name -> Poem
	0,  // 1: UploadPoemResponse.data:type_name -> Poem
	3,  // 2: PoemService.GetPoem:input_type -> GetPoemRequest
	3,  // 3: PoemService.GetPoemStream:input_type -> GetPoemRequest
	5,  // 4: PoemService.GetPoemAll:input_type -> google.protobuf.Empty
	5,  // 5: PoemService.GetPoemAllStream:input_type -> google.protobuf.Empty
	0,  // 6: PoemService.UploadPoem:input_type -> Poem
	2,  // 7: PoemService.UploadPoemStream:input_type -> StreamPoem
	1,  // 8: PoemService.BatchUploadPoem:input_type -> PoemCollection
	0,  // 9: PoemService.BatchUploadPoemStream:input_type -> Poem
	0,  // 10: PoemService.GetPoem:output_type -> Poem
	2,  // 11: PoemService.GetPoemStream:output_type -> StreamPoem
	1,  // 12: PoemService.GetPoemAll:output_type -> PoemCollection
	0,  // 13: PoemService.GetPoemAllStream:output_type -> Poem
	4,  // 14: PoemService.UploadPoem:output_type -> UploadPoemResponse
	4,  // 15: PoemService.UploadPoemStream:output_type -> UploadPoemResponse
	4,  // 16: PoemService.BatchUploadPoem:output_type -> UploadPoemResponse
	4,  // 17: PoemService.BatchUploadPoemStream:output_type -> UploadPoemResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_poem_proto_init() }
func file_poem_proto_init() {
	if File_poem_proto != nil {
		return
	}
	file_poem_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamPoem_Title)(nil),
		(*StreamPoem_Author)(nil),
		(*StreamPoem_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poem_proto_rawDesc), len(file_poem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poem_proto_goTypes,
		DependencyIndexes: file_poem_proto_depIdxs,
		MessageInfos:      file_poem_proto_msgTypes,
	}.Build()
	File_poem_proto = out.File
	file_poem_proto_goTypes = nil
	file_poem_proto_depIdxs = nil
}
