// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MessageCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []*Message             `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCollection) Reset() {
	*x = MessageCollection{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCollection) ProtoMessage() {}

func (x *MessageCollection) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCollection.ProtoReflect.Descriptor instead.
func (*MessageCollection) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageCollection) GetValue() []*Message {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"#\n" +
	"\aMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\";\n" +
	"\x11MessageCollection\x12&\n" +
	"\x05value\x18\x01 \x03(\v2\x10.message.MessageR\x05value2\x84\x02\n" +
	"\x0eMessageService\x12-\n" +
	"\x05Unary\x12\x10.message.Message\x1a\x10.message.Message\"\x00\x12@\n" +
	"\fClientStream\x12\x10.message.Message\x1a\x1a.message.MessageCollection\"\x00(\x01\x12@\n" +
	"\fServerStream\x12\x1a.message.MessageCollection\x1a\x10.message.Message\"\x000\x01\x12?\n" +
	"\x13BidirectionalStream\x12\x10.message.Message\x1a\x10.message.Message\"\x00(\x010\x01B\vZ\t.;messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_goTypes = []any{
	(*Message)(nil),           // 0: message.Message
	(*MessageCollection)(nil), // 1: message.MessageCollection
}
var file_message_proto_depIdxs = []int32{
	0, // 0: message.MessageCollection.value:type_name -> message.Message
	0, // 1: message.MessageService.Unary:input_type -> message.Message
	0, // 2: message.MessageService.ClientStream:input_type -> message.Message
	1, // 3: message.MessageService.ServerStream:input_type -> message.MessageCollection
	0, // 4: message.MessageService.BidirectionalStream:input_type -> message.Message
	0, // 5: message.MessageService.Unary:output_type -> message.Message
	1, // 6: message.MessageService.ClientStream:output_type -> message.MessageCollection
	0, // 7: message.MessageService.ServerStream:output_type -> message.Message
	0, // 8: message.MessageService.BidirectionalStream:output_type -> message.Message
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
